# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: db7a7d4d81e8337cf726268cdaa3b6413bdd6b13d0bd14bee5c1472453e4f521c05b1eda2e4be96b3bca3f58bb226d65bf5bf0dfbbf3e57dd2726337e906cf56

test:
  secret_key_base: 9e9ed0fb2b95ff8c6704e78190166ae5fc99cdfd7c4b1bc3fb663bf70af207164fce95c8d9559cfddf76a8da3ff4bbc37077ff038145d6856e9cffc00c31de79

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
